import { createClientFactory } from '../Client';
import baseModules from '../modules';
import DocumentClient from './Client';
import AudioModule from './modules/Audio';
import { CookiesModule } from './modules/Cookies';
import DOMModule from './modules/DOM';
import DOMAttributesModule from './modules/DOMAttributes';
import DOMStyleModule from './modules/DOMStyle';
import HistoryModule from './modules/History';
import IFrameModule from './modules/IFrame';
import ImageModule from './modules/Image';
import LocationModule from './modules/Location';
import NavigatorModule from './modules/Navigator';
import StorageModule from './modules/Storage';
import SyncModule from './modules/Sync';
import XMLHttpRequestModule from './modules/XMLHttpRequest';

export default createClientFactory(DocumentClient, (client) => {
	baseModules(client);
	client.addModule(HistoryModule);
	client.addModule(NavigatorModule);
	client.addModule(LocationModule);
	client.addModule(DOMAttributesModule);
	client.addModule(DOMStyleModule);
	client.addModule(DOMModule);
	client.addModule(IFrameModule);
	client.addModule(SyncModule);
	client.addModule(ImageModule);
	client.addModule(AudioModule);
	client.addModule(StorageModule);
	client.addModule(XMLHttpRequestModule);
	client.addModule(CookiesModule);
});
