import { createClientFactory } from '../Client';
import baseModules from '../modules';
import DocumentClient from './Client';
import AnchorModule from './modules/Anchor';
import AudioModule from './modules/Audio';
import ContextModule from './modules/Context';
import { CookiesModule } from './modules/Cookies';
import DOMAttributesModule from './modules/DOMAttributes';
import DOMContentHooks from './modules/DOMContentHooks';
import DOMHooksModule from './modules/DOMHooks';
import HistoryModule from './modules/History';
import IFrameModule from './modules/IFrame';
import LocationModule from './modules/Location';
import NavigatorModule from './modules/Navigator';
import StorageModule from './modules/Storage';
import SyncModule from './modules/Sync';
import XMLHttpRequestModule from './modules/XMLHttpRequest';

export default createClientFactory(DocumentClient, (client) => {
	baseModules(client);
	client.addModule(HistoryModule);
	client.addModule(NavigatorModule);
	client.addModule(LocationModule);
	client.addModule(AnchorModule);
	client.addModule(DOMAttributesModule);
	client.addModule(DOMContentHooks);
	client.addModule(DOMHooksModule);
	client.addModule(IFrameModule);
	client.addModule(SyncModule);
	client.addModule(AudioModule);
	client.addModule(StorageModule);
	client.addModule(XMLHttpRequestModule);
	client.addModule(CookiesModule);
	client.addModule(ContextModule);
});
